### ISSUE TITLE
Push the pdf to another repository for hosting

### ISSUE THREAD

**Issue by sloorush** [sloorush/resume#2]
- An extension to #1

So I also maintain this repository where I store files to be hosted. I also used to push the pdf binary to that repo manually every time there was an update.

I guess we can automate that as well since the binary is anyways built on GitHub actions now.

_Originally posted by @sloorush in https://github.com/sloorush/resume/issues/1#issuecomment-1271008964_

**Comment by Siddhant-Ray** [comment]
You can add the release path of the built PDF to the second repository. In that case, you just store the reference in the second repository, and any update is automatically linked.
